### ISSUE TITLE
How to use /api/trust ?

### ISSUE THREAD

**Issue by bmeck** [indutny/hypercorn#1]
It appears to accept *any* `feed_key` even if unknown, and any `link` (which looks like it should be optional in the [backend](https://github.com/indutny/hypercorn/blob/62d8151c6b175b7d051a7faaae1f728185cfd248/lib/hypercorn/hypercorn.js#L178-L181))?

**Comment by indutny** [comment]
It takes any trustee's `feed_key`, `expiration` which is a delta in seconds until expiration, and `description`.

This endpoint gives you an object called `Trust Link`. This object can be sent to other peers, unless the peers could just load your timeline (which has this link too).

**Comment by bmeck** [comment]
so `link` isn't needed in the body? https://github.com/indutny/hypercorn/blob/master/lib/hypercorn/schema.js#L28

**Comment by indutny** [comment]
@bmeck oh gosh, I think I broke. I just use this to validate both POST data and messages. Guess I need to have separate schema for it!
